OrgentWeb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('main.urls', namespace='main')),
    url(r'', include('users.urls', namespace='users')),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^products/$', views.products, name='products'),
	url(r'^versions/(?P<product_id>\d+)/$', views.versions, name='versions'),
	url(r'^functions/$', views.functions, name='functions'),
	url(r'^feedback/$', views.feedback, name='feedback'),
	url(r'^message/$', views.message, name='message'),
	url(r'^about/$', views.about, name='about'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
	url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
	url(r'^logout/$', views.logout_view, name='logout'),
	url(r'^register/$', views.register, name='register'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class News(models.Model):
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'News'

	def __str__(self):
		return self.text

class Feedback(models.Model):
	title = models.CharField(max_length=200)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User)

	class Meta:
		verbose_name_plural = 'Feedbacks'

	def __str__(self):
		return self.title

class Tools(models.Model):
	name = models.CharField(max_length=200)
	link = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'Tools'

	def __str__(self):
		return self.name

class Software(models.Model):
	name = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'Softwares'

	def __str__(self):
		return self.name

class Version(models.Model):
	software = models.ForeignKey(Software,on_delete=models.CASCADE)
	name = models.CharField(max_length=200)
	link = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'Versions'

	def __str__(self):
		return self.name

class Message(models.Model):
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	touser = models.CharField(max_length=200)
	owner = models.ForeignKey(User)

	class Meta:
		verbose_name_plural = 'Messages'

	def __str__(self):
		return self.text

users/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from .models import Feedback, Message

class FeedbackForm(forms.ModelForm):
	class Meta:
		model = Feedback
		fields = ['title','text']
		labels = {'title': '反馈标题', 'text': '反馈内容'}

class MessageForm(forms.ModelForm):
	class Meta:
		model = Message
		fields = ['touser','text']
		labels = {'touser': '发给（用户名）','text': '短信息内容'}

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import News, Software, Tools, Version, Feedback, Message
from .forms import FeedbackForm, MessageForm
from django.contrib.auth.decorators import login_required

def index(request):
	news = News.objects.order_by('date_added')
	context = {'news': news}
	return render(request, 'main/index.html', context)

def products(request):
	softwares = Software.objects.order_by('date_added')
	context = {'softwares': softwares}
	return render(request, 'main/products.html', context)

@login_required
def versions(request, product_id):
	software = Software.objects.get(id=product_id)
	versions = software.version_set.order_by('-date_added')
	context = {'software': software, 'versions': versions}
	return render(request, 'main/versions.html', context)

def functions(request):
	tools = Tools.objects.order_by('date_added')
	context = {'tools': tools}
	return render(request, 'main/functions.html', context)

@login_required
def feedback(request):
	feedback = Feedback.objects.order_by('date_added')
	if request.method != 'POST':
		form = FeedbackForm()
	else:
		form = FeedbackForm(request.POST)
		if form.is_valid():
			newform = form.save(commit=False)
			newform.owner = request.user
			newform.save()
			return HttpResponseRedirect(reverse('main:feedback'))
	context = {'feedback': feedback, 'form': form}
	return render(request, 'main/feedback.html', context)

@login_required
def message(request):
	message = Message.objects.order_by('date_added')
	if request.method != 'POST':
		form = MessageForm()
	else:
		form = MessageForm(request.POST)
		if form.is_valid():
			newform1 = form.save(commit=False)
			newform1.owner = request.user
			newform1.save()
			return HttpResponseRedirect(reverse('main:message'))
	context = {'message': message, 'form': form}
	return render(request, 'main/message.html', context)

def about(request):
	return render(request,'main/about.html')

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('main:index'))

def register(request):
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('main:index'))

	context = {'form': form}
	return render(request, 'users/register.html', context)

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block header %}
	<h2 align="center">关于 Orgent</h2>
{% endblock header %}

{% block content %}
	<h3 align="center">
		Copyright (c) Orgent 2018-2024 All Rights Reserved. 作者：沈彦辰 (Ethan)
	</h3>
	<p>&nbsp;</p>
	<h4 align="center">
		<a href="mailto:Contact@Orgent.top">联系我们 （Contact@Orgent.top）</a>
	</h4>
{% endblock content %}

main/templates/main/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="zh">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Orgent 官方网站</title>
		{% bootstrap_css %}
		{% bootstrap_javascript %}
	</head>
	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">展开</button>
					<a class="navbar-brand" href="{% url 'main:index' %}">Orgent 官方网站</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'main:products' %}">软件产品</a></li>
						<li><a href="{% url 'main:functions' %}">更多功能</a></li>
						<li><a href="{% url 'main:message' %}">短信息</a></li>
						<li><a href="{% url 'main:feedback' %}">发送反馈</a></li>
						<li><a href="{% url 'main:about' %}">关于我们</a></li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
							<li><a>你好，{{ user.username }}，欢迎来到 Orgent 官方网站。</a>
							<li><a href="{% url 'users:logout' %}">退出登录</a></li>
						{% else %}
							<li><a href="{% url 'users:login' %}">登录</a></li>
							<li><a href="{% url 'users:register' %}">注册</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
			<div class="page-header">
				{% block header %}{% endblock header %}
			</div>
			<div>
				{% block content %}{% endblock content %}
			</div>
		</div>
	</body>
</html>

main/templates/main/feedback.html
{% extends 'main/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>向 Orgent 发送反馈</h2>
{% endblock header %}

{% block content %}
		{% for f in feedback %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>{{ f.title }} <small>由 {{ f.owner }} 发布于 {{ f.date_added|date:'Y/m/d H:i' }}</small></h3>
				</div>
				<div class="panel-body">
					<h4>{{ f.text }}</h4>
				</div>
			</div>
		{% empty %}
			<li>当前还没有反馈。</li>
		{% endfor %}
	</ul>
	<p>&nbsp;</p>
	<h3 align="center">发布反馈</h3>
	<form action="{% url 'main:feedback' %}" method="POST" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
		<button name="submit" class="btn btn-primary">发布</button>
		{% endbuttons %}
	</form>
{% endblock content %}

main/templates/main/functions.html
{% extends 'main/base.html' %}

{% block header %}
	<h2>更多 Orgent 功能</h2>
{% endblock header %}

{% block content %}
	<ul>
		{% for tool in tools %}
			<li><h3>{{ tool.name }} &nbsp; <button onclick="javascript:window.location.href='{{ tool.link }}'" class="btn btn-primary">进入</button></h3></li>
		{% empty %}
			<li><h3>当前还未发布任何功能。</h3></li>
		{% endfor %}
	</ul>
{% endblock content %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block header %}
	<div class="jumbotron">
		<h1 align="center">Orgent 官方网站</h1>
	</div>
{% endblock header %}

{% block content %}
	<h2 align="center">海内存知己，天涯若比邻。欢迎来到 Orgent 官方网站。</h2>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
		{% for new in news %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>
						Orgent 新闻 <small>{{ new.date_added|date:'Y/m/d H:i' }}</small>
					</h3>
				</div>
				<div class="panel-body">
					{{ new.text|linebreaks }}
				</div>
			</div>
		{% empty %}
			<h3 align="center">当前还没有任何 Orgent 新闻。</h3>
		{% endfor %}
{% endblock content %}

main/templates/main/message.html
{% extends 'main/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>Orgent 短信息</h2>
{% endblock header %}

{% block content %}
	<h3>我收到的 Orgent 短信息（为空则没有收到任何短信息）: </h3>
		{% for f in message %}
			{% if f.touser == user.username %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>
						{{ f.text }} &nbsp; <small>由 {{ f.owner }} 发送于 {{ f.date_added|date:'Y/m/d H:i' }}</small>
					</h3>
				</div>
				<div class="panel-body">
					<h4>{{ f.text }}</h4>
				</div>
			</div>
			{% endif %}
		{% empty %}
			<li><h3>当前你没有收到任何短信息。</h3></li>
		{% endfor %}
	<p>&nbsp;</p>
	<h3 align="center">发送 Orgent 短信息</h3>
	<form action="{% url 'main:message' %}" method="POST" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
		<button name="submit" class="btn btn-primary">发送</button>
		{% endbuttons %}
	</form>
{% endblock content %}

main/templates/main/products.html
{% extends 'main/base.html' %}

{% block header %}
	<h2>Orgent 的软件产品</h2>
{% endblock header %}

{% block content %}
	<ul>
		{% for software in softwares %}
			<li><h3><a href="{% url 'main:versions' software.id %}">{{ software.name }}</a></h3></li>
		{% empty %}
			<li><h3>Orgent 还未发布任何软件。</h3></li>
		{% endfor %}
	</ul>
{% endblock content %}

main/templates/main/versions.html
{% extends 'main/base.html' %}

{% block header %}
	<h2>{{ software }} 的全部软件版本。 &nbsp; <small><a href="{% url 'main:products' %}">返回</a></small></h2>
{% endblock header %}

{% block content %}
	<ul>
		{% for version in versions %}
			<li>
				<h3>
					{{ version.name }} <small>发布于 {{ version.date_added|date:'Y/m/d H:i' }} </small> &nbsp;
					<button class="btn btn-primary" onclick="javascript:window.location.href='{{ version.link }}'">下载</button>
				</h3>
			</li>
		{% empty %}
			<li>当前该软件还没有任何版本可供下载。</li>
		{% endfor %}
	</ul>
{% endblock content %}

users/templates/users/login.html
{% extends 'main/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>登录到你的 Orgent 账户。</h2>
{% endblock header %}

{% block content %}
	<form method="post" action="{% url 'users:login' %}" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
		<button name="submit" class="btn btn-primary">登录</button>
		{% endbuttons %}
		<input type="hidden" name="next" value="{% url 'main:index' %}" />
	</form>
{% endblock content %}

users/templates/users/register.html
{% extends 'main/base.html' %}
{% load bootstrap3 %}

{% block header %}
	<h2>注册你的新 Orgent 账户。</h2>
{% endblock header %}

{% block content %}
	<form method="post" action="{% url 'users:register' %}" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
		<button name="submit" class="btn btn-primary">注册</button>
		{% endbuttons %}
		<input type="hidden" name="next" value="{% url 'main:index' %}" />
	</form>
{% endblock content %}